### ISSUE TITLE
easy to miss validity intervals

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#117]
@hardie notes that the not_before and not_after fields are there and described, but not really part of the operational notes.  Having something there that talks about these, particularly as it relates to clock skew, would be valuable.

**Comment by sftcd** [comment]
(My ~monthly login into github.com - this'd be better on the TLS WG list, and I will send mail on this sometime but anyway...)
The not-before and not-after fields are a mistake.
Same as turned out true for x.509.
I was just doing testing where FF nightly barfed on ESNIKeys I'd published for only that non-reason. (There is no overall security win in so-doing, in general.)
Creating a tangle between the cadence at which one updates DNS, the ESNIKeys-internal "lifetime" of a key, the DNS TTL and server-state is basically just pointless nonsense. 
Let's delete those fields from ESNIKeys before we're done and just rely on DNS for what it already does.

**Comment by kazuho** [comment]
Now that #124 has been merged, I agree that there is less need for not_before and not_after fields. Previously, a client using an expired key led to connection failures, and therefore having these fields were necessary.

**Comment by chris-wood** [comment]
Fixed by removing these fields with #161.
