### ISSUE TITLE
Interaction with Alternative Services is confusing

### ISSUE THREAD

**Issue by DavidSchinazi** [tlswg/draft-ietf-tls-esni#132]
The draft currently states:

> In cases where the domain of the A or AAAA records being resolved do not match the SNI Server Name, such as when {{!RFC7838}} is being used, the SNI domain should be used for querying the ESNI TXT record.

I'm confused about what this means. From reading RFC 7838, I'm not sure the SNI and DNS names do not match when you're querying an alternate name. In particular, RFC 7838 states:

> For example, if the origin's host is "www.example.com" and an alternative is offered on "other.example.com" with the "h2" protocol, and the certificate offered is valid for "www.example.com", the client can use the alternative.

Which means, if I understand it correctly, the client will send "other.example.com" in the SNI when trying to query resources from it - the requirement is only that the certificate for "other.example.com" also cover "www.example.com".

**Comment by chris-wood** [comment]
Agreed. I'm parsing RFC 7838 the same way. I think we should drop this text.

**Comment by mcmanus** [comment]
The problem the text presents is real (though the resolution is arbitrary).

> Which means, if I understand it correctly, the client will send "other.example.com" in the SNI when trying to query resources from it - the requirement is only that the certificate for "other.example.com" also cover "www.example.com".

no.. that's a misread. See section 2.3 of 7838
```
 Note that the SNI information provided in TLS by the client will be
   that of the origin, not the alternative (as will the Host HTTP header
   field value).
```

The alternate is essentially just a cname for the origin. If host b is an alternate for origin a, in order to use the alternate you look up the DNS a/aaaa of b, do a TCP connect to b, and then use sni=a and expect a certificate valid for a.

With esni you would continue to do all of those things, except of course sni=encrypted(a).. and the question becomes where do you find the key used for the encryption. Is it the ESNI DNS record of a (the origin) or b (the alternate host). That's the question the text is trying to resolve - it says to use a (the origin). I could make a case for either choice but I think the text needs to decide (the logic of the choice is largely that if the alt-svc were a cname it would delegate all record types, including the esni)

**Comment by chris-wood** [comment]
@mcmanus Would you mind suggesting some text with an example to clear this up?

**Comment by DavidSchinazi** [comment]
@mcmanus thanks for the clarification and pointer to s2.3 of 7838. After reading that I think the text in the ESNI draft looks fine. (I'd just add a pointer to s2.3 of 7838 instead of just 7838 to help prevent the confusion I had)
