### ISSUE TITLE
record_digest should not cover address_set

### ISSUE THREAD

**Issue by davidben** [tlswg/draft-ietf-tls-esni#150]
Filing this so we don't forget:

Currently the record digest covers the address_set extension. This means adding a new addresses to a deployment introduces new digests that need to be propagated to all servers to recognize. (Unless servers trial decrypt everything, but then record digests aren't doing anything.)

Perhaps the A/AAAA + ESNI gluing should external to the ESNIKeys structure. The glue is probably assembled by DNS serving logic, while ESNIKeys is otherwise probably an opaque blob assembled by some key provisioning system.

**Comment by ghedo** [comment]
Made #151 to try to address this by excluding extensions from the digest. A DNS server that knows it will generate extensions can keep the rest of ESNIKeys as blob, and then simply append extensions to it when serving the record. Otherwise I wouldn't know where to put the AddressSet thingy.

**Comment by davidben** [comment]
What do you think about splitting it in two layers?

First you've got ESNIKeys as it existed prior to address_set. The record digest covers the whole thing as before. DNS believes it's just an opaque blob.

Then you've got, say, some BUNDLE RRTYPE whose RDATA encodes a list of (RRTYPE, RDATA) tuples in whatever DNS-y syntax people want. The DNS server then just assembles a BUNDLE with A and AAAA formatted as before, plus an ESNI record with it. This avoids this odd situation we have here where ESNI wants to be the root of the tree, to the exclusion of everyone else who may wish to correlate data with A/AAAA.

A nuisance here: we do want to avoid the client having to ask for all of A, AAAA, ESNI, *and* BUNDLE. It is more risk of performance problems and acting on any response to ESNI would reintroduce multi-CDN woes. We'd have to say ESNI can only be fetched via BUNDLE or so. (That perhaps suggests the "keys" in BUNDLE should be its own namespace? Other than A/AAAA, everything else is likely to never be fetched on its own.)

**Comment by ghedo** [comment]
I agree that the problem is really in DNS, and a complete solution needs to happen there. However I think it's orthogonal to ESNI, and should probably be discussed on its own (e.g. in dnsop).

There was some talk in Prague about doing that but AFAICT nothing happened yet, so I'd be interested in helping put a  BUNDLE proposal together if nothing else comes up, and see what the DNS people think.

In the meantime AddressSet is what we have, and it's probably easier to just make that work for the specific ESNI case in the short term, and then replace it with whatever BUNDLE solution comes out later on, so the two discussions can proceed in parallel.

**Comment by davidben** [comment]
Well, we don't have anything right now because address_set doesn't work. :-P We can change the syntax however we like, be it defining BUNDLE in the ESNI doc, or doing something dumb like:

```
struct ESNIKeysWithAddresses {
  ESNIKeys keys;
  Address address_set<0..2^16-1>;
}
```

**Comment by kazuho** [comment]
My +1 goes to doing this hack, assuming that it helps somebody deploying ESNI.

If it turns out to be a bad idea, we can switch to a different mechanism by just bumping the version number in ESNIKeys.

**Comment by ghedo** [comment]
@davidben yeah, so that's similar to @chris-wood's proposal of just having an additional extensions field that doesn't go into record_digest. The additional extensions field would be somewhat more flexible and accomodate both address_set and the other multi-CDN proposal if it ever shows up. Do we care about this flexibility?

I find both solutions kinda yucky, but I guess those are the options we have. I can update my PR (or create a new one) with whatever new hack.

**Comment by ghedo** [comment]
Actually, I don't know if the other multi-CDN proposal would have the same problem, so maybe the extensibility is not needed?

**Comment by chris-wood** [comment]
@ghedo @davidben @kazuho @ekr 

How about:

~~~
struct {
  ESNIKeys keys;
  Extensions dns_extensions<0..2^16-1>;
} ESNIKeysWithExtensions;
~~~

We can then put address_set in dns_extensions, and TLS stacks don't ever have to see them.

**Comment by ghedo** [comment]
Yeah, was thinking something along those lines, I'll see if I can put it into text in the next few days if nobody beats me to it.
