### ISSUE TITLE
Clarify 1.2 connection support (don't break connections, but also don't protect the certificate)

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#214]
If the backend server does not include any signal for ECHO negotiation, either as a ServerHello extension or part of ServerHello.random, then it's possible to tunnel CHs to TLS 1.2 servers. This can be a feature, so let's consider whether or not it's in scope. (Note that we may discover that lack of server-side handshake message padding may make traffic analysis trivial.)

cc @grittygrease

**Comment by sftcd** [comment]
Not sure that'd be worthwhile. Wouldn't the TLS server cert be sent in clear to the client? So the server-name will be visible anyway. I'm not sure if the remaining CH content is sufficient to justify the added complexity of having to handle a TLSv1.2 CH.

**Comment by chris-wood** [comment]
If we didn't encrypt the server flight, that's right! But we might consider designs wherein the client-facing server encrypts (or tunnels) the server flight, just as we've done for the client flight.

**Comment by sftcd** [comment]
Ah, so support for TLSv1.2 here implies a new middle->client encryption. My first reaction is that we're nearly inventing masque again, so maybe this is a feature to leave for that?

**Comment by chris-wood** [comment]
> Ah, so support for TLSv1.2 here implies a new middle->client encryption. My first reaction is that we're nearly inventing masque again, so maybe this is a feature to leave for that?

Possibly. There may be a middle ground. Considering the amount of TLS 1.2 servers in existence, I think this is worth some thought.

**Comment by ekr** [comment]
This seems clever, but on balance it seems like we are getting close to a "tunnel everything" design. We want people to move to 1.3 and so going out of our way to accommodate 1.2 seems backwards.

**Comment by grittygrease** [comment]
The main problem this solves is in the fronting case. Specifically, in the
case that an ECHO-aware fronting server is operated by a different entity
than the backend server and the fronting server does not know whether the
backend server supports TLS 1.3 or not. Enabling support for TLS 1.2
enables this fronting server to be deployed in front of a wide set of
servers.

**Comment by kazuho** [comment]
As others have pointed out, the cost of adding support for TLS 1.2 servers it that there needs to be a layer below the TLS record layer, so that the plaintext records sent by the backend server can be encrypted.

I'd be a bit concerned about the required cost and complexity that that has, therefore my +1 goes to just supporting TLS 1.3.

**Comment by bemasc** [comment]
Two concerns here:

1. Security: Suppose an adversary can inject a TLS 1.2 ServerHello, without the echo_nonce, and a Certificate message.  Does the client react differently depending on whether the hidden name is in the SAN list (e.g. certificate mismatch fails faster than verification failure)?  If so, the adversary might be able to learn the hidden name.

2. Management: Suppose a TLS 1.2 backend is not coordinating closely with forwarder, which seems to be the goal of this model.  When the backend upgrades to TLS 1.3, will connections start failing because it is not including the echo_nonce in the transcript?

**Comment by chris-wood** [comment]
The client reaction issue is interesting, though maybe we can get around that by requiring constant time verification? Hmm... penny for your thoughts, @ekr and @davidben?

As for the nonce issue -- it's already included in the ClientHello. The server doesn't include it an extension explicitly.

**Comment by bemasc** [comment]
Thanks for the clarification.  I still think there's a potential best-practices concern if this encourages deployments that transmit the decrypted ClientHello in cleartext between the forwarder and backend, but that's less obvious.

**Comment by chris-wood** [comment]
Agreed! Clarifying text there would help. I'll see if I can craft something along those lines for this issue.

**Comment by sftcd** [comment]
FWIW, I still think making complexity-inducing changes
to better support TLSv1.2 (even in this reduced manner)
would be a bad plan. In large part because it'd take ages to figure it
out. If someone could demonstrate a reduction
in complexity and increase in security I might change my
mind. Absent that, I continue to think we're better off
exclusively supporting TLSv1.3.

Cheers,
S.

**Comment by davidben** [comment]
The issue of not being able to clearly tell whether ServerHello used the outer or inner ClientHello does seem somewhat fatal. Deferring figuring this out to certificate verification is especially a nuisance, and I shudder at the thought having a coherent notion of constant-time X.509 verification.

**Comment by ekr** [comment]
I think we should continue to base this on the assumption that the server does TLS 1.3. Trying to analyze the question of how this integrates with TLS 1.2  -- especially given that we have concerns about the naive integration -- seems prohibitive.

**Comment by chris-wood** [comment]
On reflection, I tend to agree. On platforms I'm familiar with, constant-time certificate verification would be intractable. I'm closing this issue with the recommendation that we stick to the document's intent: ESNI for TLS 1.3.
