### ISSUE TITLE
Clarify ECHOConfig (HTTPSSVC) extension purpose

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#216]
ECHOConfig.public_name provides information that goes in the outer CH. HTTPSSVC.alpn provides information to go in the inner CH (I assume). We don't specify a way for the server to  explicitly say what alpn to use in the outer CH.  I think it'd be worth re-considering where servers/admins might want to put that kind of information and how much of the inner/outer CH they may want to describe. There could be a range of potential outcomes if we re-visit this - at one extreme HTTPSSVC or ECHOConfig might provide a template for the entire CH (possibly via some template naming/numbering scheme), at the other extreme we might decide that ECHOConfig should only contain the keying information and just define alpn, public_alpn and public_name as optional fields for inclusion in HTTPSSVC. But it seems a bit broken for the only two parts of the CH the server specifies to be handled so differently,

**Comment by davidben** [comment]
> HTTPSSVC.alpn provides information to go in the inner CH (I assume).

It doesn't. It's important for downgrade protection that the DNS (not secured) *not* impact the client's ALPN preferences. The interaction between HTTPSSVC and ALPN is... rather a mess and the text around this still needs work.

**Comment by sftcd** [comment]
On 13/04/2020 15:54, David Benjamin wrote:
>> HTTPSSVC.alpn provides information to go in the inner CH (I
>> assume).
> 
> It doesn't. It's important for downgrade protection that the DNS (not
> secured) *not* impact the client's ALPN preferences. The interaction
> between HTTPSSVC and ALPN is... rather a mess and the text around
> this still needs work.

Ah. Fair enough. Though I guess ECHO will likely only be
used via DoH or something equivalent which could change
things maybe.

But regardless... doesn't the point still stand that we'd
be better off with some consistency in how we manage the
server-name in the outer CH, the ALPNs in both inner and outer, and any
other CH content where the server wants to
publish some hints?

I'm not particularly wedded to a specific approach (though
I'd likely be more biased to simplifying the ECHOConfig).

**Comment by davidben** [comment]
Even DoH won't authenticate the origin, only the resolver. One hopes the resolver is reasonably trusted, but I'd still prefer not giving it new powers. (Today, only the origin server pick HTTP/1.1 vs HTTP/2. That's useful given HTTP/1.1's safety against truncation attacks is... complicated.)

I guess I see the public name less as an instruction for what to put in the outer ClientHello but a delegation to another name to authenticate any ECHO key replacements or ECHO shutoffs. That then implies putting it in the outer ClientHello so the server can pick the right fallback certificate. I think I'd also rather keep that information in ECHOConfig so the TLS stack gets a single bundle of data. (Similar thinking as https://github.com/tlswg/draft-ietf-tls-esni/issues/219#issuecomment-612963381.) But maybe the overall change would make more sense? I don't fully understand the proposal.

Of course, the same authentication mismatch applies to the public name as any ALPN signals. While this was ESNI rather than ECHO, the reasoning was that the DNS server learns the hostname anyway, and can pretend ESNI wasn't deployed. The latter still holds for ECHO. The former... I'm not sure. Over in browser land, I really only care about the hostname, but there are probably other scenarios.

**Comment by bemasc** [comment]
Assuming we are trying to do GREASE, the important thing is that the outer ClientHello is the same for clients with real and fake ECHO.  This could be achieved by providing a template in the ECHOConfig for the outer ClientHello that matches a popular client's behavior, or by telling clients "when constructing the outer ClientHello, pretend you're connecting to the public name without the HTTPSSVC info".  For now, I would lean to the latter for simplicity.  We can always define an outer ClientHello template later as an ECHOConfig extension.

If we give up on GREASE, I would remove the outer ALPN entirely.

**Comment by davidben** [comment]
The latter sounds reasonable.

A template would not fly because the outer ClientHello must still adhere to [protocol invariants](https://tools.ietf.org/html/rfc8446#section-9.3), so any parameters in there must ones the client would legitimately accept. (Unless they ignore the fallback case and retry all errors with a more accurate outer ClientHello.)

**Comment by chris-wood** [comment]
As per the call today, we'll use this issue to track guidance (that will be mirrored in the HTTPSSVC document) about how one populates extension information. In particular, information that pertains to the outer CH, which exists only for ECHO's sake, should be limited to ECHOConfig, whereas information that pertains to the inner CH should be put in the HTTPSSVC.

**Comment by chris-wood** [comment]
Fixed in #226. Closing.
