### ISSUE TITLE
Use HPKE codepoints for all HPKE-relevant operations

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#218]
HPKE has it's own cipher suite code points, as well as the KEM id. I don't see why we're using TLS codepoints (ECHOConfigContents.suites and ClientEncryptedCH.suite) and yet also use one HPKE code point (ECHOConfigContents.kem_id). But maybe I'm missing something?

If not, I think one of two things would make sense:

1. Change HPKE to use TLS code points. (That could be done but'd involve a bit of nose-holding, however it might be better in the longer term.)
2. Only use HPKE code points in ECHO - I don't see that TLS ciphersuites are actually needed for ECHO, so this seems easiest. (That'd mean s/suite/aead_id/g I guess.)

**Comment by ekr** [comment]
I tend to agree with Stephen here. ISTM that probably (1) is better, actually.

**Comment by chris-wood** [comment]
I don't think we want HPKE to depend on TLS code points. Algorithms that come down the pipe may not be suitable for TLS. I'd prefer option (2).

**Comment by bifurcation** [comment]
There's also a third option here:

3. Use TLS code points (or something else) and define a mapping to HPKE code points

Like @chris-wood, I am disinclined to tie HPKE to TLS, since it is a more general tool.

It seems like the answer here depends on what the negotiation in ECHO is being used for.  If it's just for the HPKE, use HPKE code points.  If it's used in TLS further down the line, use TLS code points and map to HPKE for the HPKE bits.

**Comment by ekr** [comment]
How is (3) different than the current design?

**Comment by chris-wood** [comment]
Per the call today, we'll use this issue to track moving everything to HPKE codepoints. (We can remove the mapping table at the same time).
