### ISSUE TITLE
Restrict ECHO inner/outer variance for interop purposes

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#223]
First, I do think the security analysis for ECHO ought consider that the inner can be entirely different from the outer. That does not mean that we need to make full use of that flexibility when considering interop.

In the ECHO coding I've done so far, handling more restricted variation between inner and outer is a lot simpler, code-wise, and I would expect, will make interop easier and more successful. It seems (at least with OpenSSL) that once the cryptographic parameters (e.g. key shares) are allowed to vary between inner and outer, then things get significantly more complex. (That's not only down to
the trial decryption on the client btw, but is clearly demonstrated by the need for trial decryption.)

I suggest we consider, for now, restricting how the inner and outer can vary, for example, only requiring implementations be able to handle minimal variation, perhaps only with server name and alpn and the nonce and ECHO that have to differ.

If, having coded this up, people figure it is actually  easy enough to support more flexibility then we could change to require support for that later. I think we should be able to decide before WGLC or IETF LC but don't believe we can currently be confident that full flexibility would be a good interop choice.

**Comment by ekr** [comment]
You need trial decryption on the client no matter what, because the transcript will be different, so that's not relevant here.

I am not in favor of restricting how the inner and outer can vary. This is precisely the kind of thing that implementations might then get wrong by assuming and then we have problems.

It seems to me that your primary argument here is implementation difficulty, plus some speculation about interop. I don't anticipate any difficulty implementing this in NSS based on my experience with HRR, and it seems like we'll find out whether there are interop difficulties soon enough, so adding restrictions is premature.

**Comment by chris-wood** [comment]
Per the call today, we're closing this for now. We may revisit this later on if more implementation experience from the WG leads folks towards a restrictions on inner/outer variance.
