### ISSUE TITLE
Trial decryption after HelloRetryRequest

### ISSUE THREAD

**Issue by ocheron** [tlswg/draft-ietf-tls-esni#233]
In a normal ECHO handshake with HelloRetryRequest there are 4 ClientHellos sent: ClientHelloOuter1, ClientHelloInner1, ClientHelloOuter2, ClientHelloInner2.

Encryption of ClientHelloInner2 is bound to echo_hrr_key so the server must have the ECHOConfig used for ClientHelloInner1 in order to process ECHO the second time.
And by the time the client receives encrypted handshake traffic it is not useful to signal if ClientHelloInner1 was successfully decrypted, what matters is to know if ECHO is globally successful or not.

So one aspect that I find not explained enough is whether the server replying with HRR should use ClientHelloInner1 in the transcript, or instead always takes ClientHelloOuter1 (data on the wire) regardless of the first decryption status. The ECHO status accept/reject can be conveyed based on distinction ClientHello2 inner/outer only.

This point impacts the number of transcripts the client may have to try, i.e. can be sure the combination (ClientHelloInner1, ClientHelloOuter2) is never valid.

**Comment by cjpatton** [comment]
Hi @ocheron, the spec has changed quite a bit since this question was first posed. In particular, we've landed #287, which changes the server behavior so that it provides an explicit signal of ECH acceptance in its SH. Hence, no more trial decryption. I'm wondering if your question still applies?

I believe what to do in case of HRR is well-specified at this point. There is no such ECH accdeptance signal provided in the HRR, so to determine if ECH was accepted, the client must wait until the SH. Until that point, the client needs to compute two transcripts in parallel: one assuming the ClientHelloOuter was used, and another assuming the ClientHelloInner was used.

**Comment by davidben** [comment]
I don't think #287 resolves this. If the client has different HRR-relevant preferences (key share and cipher suite) between CHInner and CHOuter, I believe HRR is still a mess because the HRR message doesn't contain a signal for whether ECH was accepted. Though I suppose it is a little less complex now that you don't need to go as far as trial decrypting. Different HRR-relevant preferences means the HRR may be good for one ClientHello but not the other, yet the client needs to manage that state and defer the actual error-handling to when ECH acceptance is known. An option where the HRR message included an ECH acceptance signal would close this, but then we have sticking out woes.

The draft touches on this, but somewhat vaguely.
https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-6.3.3-1

We've been intending that our implementation would always match inner and outer preferences for HRR-sensitive fields, to avoid this case. But having this odd complexity cliff hidden in the spec is poor. I'd advocate we either require or at least strongly recommend clients do this.

**Comment by cjpatton** [comment]
#308 suggests to add the following text to the HRR section: 

> It is an error for the client to offer ECH before the HelloRetryRequest but not
after. Likewise, it is an error for the client to offer ECH after the
HelloRetryRequest but not before. If the client-facing server accepts ECH for
the first ClientHello but not the second, or it accepts ECH for the second
ClientHello but not the first, then it MUST abort the handshake with an
"illegal_parameter" alert.

I think this solves the problem, at least partially.

**Comment by davidben** [comment]
That doesn't address the problem. This is about complexity for the client, not the server. Yes, the server needs to enforce consistency between the two modes, but it is easy for it to do this.

Imagine you're the client and your CHOuter has:
* key_shares = {X25519}
* supported_groups = {X25519, P-256, P-384}
* cipher_suites = {TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384}

And your CHInner has:
* key_shares = {P-256}
* supported_groups = {X25519, P-256, P-384}
* cipher_suites = {TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256}

Now consider how you have to respond to each of these HRRs. Remember that at the time you process the HRR, you *don't know if ECH was accepted*.
1. cipher_suite = TLS_AES_256_GCM_SHA384; key_share = P-384
2. cipher_suite = TLS_AES_128_CCM_SHA256; key_share = P-521
3. cipher_suite = TLS_CHACHA20_POLY1305_SHA256; key_share = X25519
4. cipher_suite = TLS_AES_128_GCM_SHA256; key_share = P-256
5. cipher_suite = TLS_CHACHA20_POLY1305_SHA256; key_share = X25519

1 is valid for both ClientHellos. This is the easy case and you can compute new CHInner and CHOuter values.
2 is valid for neither ClientHello. If you can detect this, you can error immediately.
3 is valid for neither ClientHello, but for messy reasons. The key share is valid for CHOuter but the cipher suite is not. The cipher suite is valid for CHInner but the key share is not. (Recall that a key share in HRR is allowed if it is in CH.supported_groups and *not* CH.key_shares. If it were in CH.key_shares, you shouldn't have sent HRR.)
4 is valid for only CHOuter, so you can't error. It is not possible to compute a CHInner, so I guess you drop the extension? But you still need to make a note to raise an error later if you see SH which claims it did accept ECH.
5 is valid for only CHInner, so you can't error. It is not possible to compute a CHOuter, but you have to, so I guess you send something garbage? But you still need to make a note to raise an error if you see SH which claims it rejected ECH.

This is a huge mess. The client can avoid this mess by always matching key_shares, supported_groups, and cipher_suites between CHInner and CHOuter. That means it can process HRR without knowing which CH to use. It is not obvious in the spec that you should do this, and the spec allows you to not do this.

**Comment by cjpatton** [comment]
I see, I wasn't thinking about client complexity. Thanks for laying out the various edge cases. I would favor being stricter about how the key_shares, supported_groups, and cipher_suites are chosen. At the very least, we should guide implementations towards ensuring they are the same in the CHInner and CHOuter.

**Comment by ocheron** [comment]
> I'm wondering if your question still applies?

I think there is still ambiguity in the design about what CH is used by the client-facing server in its own transcript when forwarding CHInner to the backend server. Or else the combination (ECH accepted before HRR, ECH rejected after HRR) can be explicitly forbidden, but I don't see why/how.

**Comment by cjpatton** [comment]
> Or else the combination (ECH accepted before HRR, ECH rejected after HRR) can be explicitly forbidden, but I don't see why/how.

Incidentally, this is addressed by https://github.com/tlswg/draft-ietf-tls-esni/pull/311. This adds the following to client-facing server behavior: 

> It is an error for the client to offer ECH before the HelloRetryRequest but not
after. Likewise, it is an error for the client to offer ECH after the
HelloRetryRequest but not before. If either of these conditions occurs, then the
client-facing server MUST abort the handshake with an "illegal_parameter" alert.

It's not hard for the client-facing server to enforce this. It just needs to remember if an HRR was triggered and whether ECH was offered in in the first CH.

**Comment by ocheron** [comment]
Ok that will do it.
Assuming "ECH not offered" is same as "ECH not accepted", due to greasing.
