### ISSUE TITLE
Security considerations: SNI leakage vectors

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#266]
Section 7.1 provides a bit of guidance on how ECH might interact with other extensions:

> The client MUST place the value of ECHConfig.public_name in the ClientHelloOuter
"server_name" extension. The ClientHelloOuter MUST NOT contain a "cached_info"
extension {{!RFC7924}} with a CachedObject entry whose CachedInformationType is
"cert", since this indication would divulge the true server name. The remaining
contents of the ClientHelloOuter MAY be identical to those in ClientHelloInner
but MAY also differ.

I think it's worth expanding on this in "Security Considerations". There may be other ways that private CH extensions get leaked, now or in the future.

**Comment by davidben** [comment]
Now that we've switched to encrypting an entire ClientHello, I think the text wants to say something else anyway: if you want ECH + cached info, you simply include the cached_info extension in the ClientHelloInner, not the ClientHelloOuter. There wouldn't be much point in sending a true name cached_info in ClientHelloOuter since the true server would ignore it. Sending a public name cached_info in ClientHelloOuter is also plausible and also needn't be forbidden (it reveals information about the public name, which is public). It's also probably not that useful since it's just a recovery mechanism, but maybe to avoid sticking out, for clients that normally send it?

More generally, anything dependent on the inner name goes in ClientHelloInner and not ClientHelloOuter.

**Comment by davidben** [comment]
I took a stab at replacement text in https://github.com/tlswg/draft-ietf-tls-esni/pull/270. Thoughts?

**Comment by cjpatton** [comment]
I'm happy with it.
