### ISSUE TITLE
Rejecting ECH for unrecognized backend servers

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#289]
The client-facing server should not attempt to accept ECH on behalf of backend servers it doesn't recognize. For example, suppose a client attempts to connect to "example.com" via an ECH-service provider named "ech-provider.com", but "example.com" has not authorized "ech-provider.com" to accept ECH on its behalf. What should the client-facing server do in this case? It could reject ECH, but this action alone doesn't convey the reason ECH was rejected. The reason is important here because the client might not know that "example.com" is unreachable via  "ech-provider.com".

@Lekensteyn proposed adding the following behavior to "Client-Facing Server Behavior":

> If the client-facing server does not have the authority to accept ECH on the backend server's behalf, e.g., it does not recognize the value of the "server_name" extension sent in the ClientHelloInner, then it SHOULD abort the handshake with an "unrecognized_name" alert.

This alert is appropriate because the situation is akin to the server getting a plaintext SNI for which it is not authoritative. I think "SHOULD" is more appropriate than "MUST" because what it means for the client-facing server to "have the authority to accept ECH on behalf of the backend server" is deployment-dependent. In the CDN case it's quite clear what this means: the client-facing server is only authoritative for websites on its platform. But other use cases are less clear.

**Comment by Lekensteyn** [comment]
By "authority" I meant that the backend is not able to produce a certificate to serve the requested name in SNI (either plaintext or in encrypted form). (The difference between shared and split mode is not important for this logical distinction between "client-facing server" and "backend server".)

Some more context on why rejection is not appropriate. Given a CH with the ECH extension, the server can act in some ways (based on Section 3.2):

1. ECH not supported by client-facing server. Proceed as usual.
2. "ECH rejection"
   a. No ECHConfig was found for the given `config_digest`. The client-facing server rejects and sends a `retry_configs` extension.
   b. A valid ECHConfig was found, but decryption fails. Server aborts with a `decrypt_error` alert. (Note an ambiguity on "decryption failure" - I filed #290 for that.)
3. "ECH acceptance"
  a. A valid ECHConfig was found, and the backend is authoritative for the decrypted SNI. Client-facing server accepts.
  b. A valid ECHConfig was found, and the backend is not authoritative for the decrypted SNI. (This issue.)

In case (3b), rejecting as is done in (2a) is wrong because the next retried connection will fail similarly.

In the current specification, the decrypted CH is forwarded to the backend and is treated as "ECH acceptance". The backend could subsequently send an "unrecognized_name" alert instead of the Server Hello, send a default self-signed certificate, etc. Whether the backend is authoritative is invisible to the client-facing server.

However if #283 gets implemented, ECH confirmation will be explicit and requires backend cooperation. This is not possible if the backend sends an alert before the Server Hello. Rejection on the other hand is also not valid for the reason mentioned before. Hence the explicit suggestion for an alert.

**Comment by davidben** [comment]
Is there a reason the behavior for an unknown encrypted server name needs to be different from seeing an unknown public server name? I would have expected the ECH logic, after decrypting the inner ClientHello, just passes it along to the same ClientHello dispatching logic as usual.

That is, the text in https://tools.ietf.org/html/rfc6066#section-3 which recommends either `unrecognized_name` or continuing with I guess a default backend. I'm not entirely sure why folks continue with default backend when the client has explicitly told you what name it wants, but whatever.

In particular, I expect TLS implementations which expose a callback for selecting certificates will just call the callback with the inner ClientHello information, and let the application continue with whatever it normally wants. That way adopting ECH requires fewer changes to server software.

**Comment by cjpatton** [comment]
> Is there a reason the behavior for an unknown encrypted server name needs to be different from seeing an unknown public server name? I would have expected the ECH logic, after decrypting the inner ClientHello, just passes it along to the same ClientHello dispatching logic as usual.

Nope, these should be treated the same! The semantics of the "server_name" extension cover this. Thanks for pointing it out.

(I'll close this issue once @Lekensteyn has had a chance to chime in.)

**Comment by chris-wood** [comment]
@cjpatton it might be worth noting that servers ought to treat these two the same. Perhaps we can use this issue to track that?

**Comment by Lekensteyn** [comment]
I agree that the TLS stack should treat the unencrypted SNI and successfully decrypted SNI the same way. This could be made explicit if not already, but I still wonder how it interacts with #283 adding changes to the Server Hello (which seems to break Split Mode in any case).

I would be fine closing this issue (with or without the clarification) and defer this lack of ECH acceptance signal to #283.

**Comment by cjpatton** [comment]
@chris-wood 

> it might be worth noting that servers ought to treat these two the same.

I think this is implied by the following paragraph in the spec:

> Upon determining the true SNI, the client-facing server then either serves the connection directly (if in Shared Mode), in which case it executes the steps in the following section, or forwards the TLS connection to the backend server (if in Split Mode). In the latter case, it does not make any changes to the TLS messages, but just blindly forwards them.

So think mentioning this is a bit redundant. I would suggest closing this issue without changing the text.

**Comment by chris-wood** [comment]
Yeah, on reflection, you may be right. Closing.
