### ISSUE TITLE
Ensuring 1.3 is used when ECH is accepted

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#309]
Usage of 1.3 is enforced by the following rules.

* Client (Section 6.1):
    > It MUST offer to negotiate TLS 1.3 or above [in ClientHelloOuter]. [...] It MUST NOT offer to negotiate TLS 1.2 or below [in ClientHelloInner].

* Client-facing server (7.1):
    > Upon receiving an "encrypted_client_hello" extension, the client-facing server MUST check that it is able to negotiate TLS 1.3 or greater. If not, it MUST abort the connection with a "handshake_failure" alert.

* The backend server does not enforce 1.3 usage. (At least, I couldn't find an explicit rule in the text.)

Requiring that 1.3 is the only version offered in the ClientHelloInner is sufficient to ensure that 1.3 is negotiated by the client and backend server in case of acceptance. However, my sense is that the client would be easier to implement if this rule were softened to:

> It MUST offer to negotiate TLS 1.3 in the ClientHelloInner.

We could then add the following behavior to the backend server (Section 7.2):

> If the ClientHelloInner indicates ECH was accepted [i.e., there is an empty "encrypted_client_hello" extension in the ClientHello], but the client does not offer support for TLS 1.3 or above, then the backend server MUST abort the handshake with a "[some error]" alert.

What do y'all think?

**Comment by cjpatton** [comment]
I'm happy to put together a PR if folks are happy with this change.

**Comment by davidben** [comment]
I don't feel strongly either way. I actually hadn't realized the client was already forbidden from offering TLS 1.2. The server needs to check anyway, and it's much more natural to check the negotiated version, so I don't think it helps the server in either direction. (@dmcardle since we were talking about this recently.)

There's no real reason for the client to offer TLS 1.2 in the inner ClientHello, and it could send a potentially smaller ClientHello (fewer cipher suites, omit renegotiation_info, extended_master_secret, shorter supported_versions). One footnote is a shorter supported_versions is still more bytes than a compressed supported_versions, but I think the savings elsewhere exceed that. (At least for now. Maybe 10 years from now, there will be very few TLS 1.2 ciphers and very many post-TLS-1.2 versions before TLS 1.2 is gone??)

I guess the other factor is it may also be more convenient for the client not to have juggle two different min_version values around in its ClientHello construction logic. But I feel like the client should decide based on how many bytes it takes on the wire.

**Comment by cjpatton** [comment]
> @davidben: The server needs to check anyway, and it's much more natural to check the negotiated version, so I don't think it helps the server in either direction.

Which server? the client-facing server or the backend server? AFAICT the backend server doesn't currently enforce the version.

**Comment by davidben** [comment]
I mostly do not believe in split mode, but I suppose it'd be the client-facing server. I suppose that's a little odd since the client-facing server isn't the one that negotiates a version. But either way, both the existing text and your proposed replacement discusses the negotiated version.

**Comment by cjpatton** [comment]
I would favor relaxing the requirement on the client side and having the backend server abort if 1.3 isn't offered. It seems conceptually cleaner, since it reduces the amount of things one has to think about when constructing the ClientHelloInner.

**Comment by chris-wood** [comment]
> I would favor relaxing the requirement on the client side and having the backend server abort if 1.3 isn't offered. It seems conceptually cleaner, since it reduces the amount of things one has to think about when constructing the ClientHelloInner.

I would argue that this is *less* clean, since it requires us to also specify client behavior in the event of a 1.2 SH (which could maliciously be inserted by someone between the client-facing and backend server). Beyond that, I don't see why prohibiting everything below 1.3 in ClientHelloInner is cleaner. This is a protocol for TLS 1.3, so why continue adding legacy cruft where it can't possibly be used?

**Comment by cjpatton** [comment]
> I would argue that this is _less_ clean, since it requires us to also specify client behavior in the event of a 1.2 SH (which could maliciously be inserted by someone between the client-facing and backend server).

Good point!

> This is a protocol for TLS 1.3, so why continue adding legacy cruft where it can't possibly be used?

The idea is that it would make implementing the client easier. I don't have a strong opinion either way, so I'm happy to drop this and go with the status-quo.

**Comment by cjpatton** [comment]
In fact, @chris-wood's observations means it's probably a wash :/

**Comment by cjpatton** [comment]
Closing as resolved. No action taken.

**Comment by davidben** [comment]
#319 made me realize there's more weird things around the version text. The client-facing server text doesn't even make sense because it's a check on the outer ClientHello, rather than the inner ClientHello. This means that actually no checks on the server side ensure we don't accidentally negotiate TLS 1.2 and leak the server name, and the client text in 6.1 is actually load-bearing.

I'll upload a PR to fix up the 7.1 text. Maybe also worth an optional sanity-check in Shared Mode? Not sure.
