### ISSUE TITLE
Include ECH context in ClientHelloOuterAAD

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#326]
@davidben mentions possibly binding the outer CH to the ECH encryption in #323. If we don't do that, we should at least bind the encryption to the non-encrypted parts of the ECH extension (`config_id`, `suite`, and so on).

cc @cjpatton

**Comment by chris-wood** [comment]
Closing in favor of #323. We can revisit the ECH extension AD information later if desired.

**Comment by chris-wood** [comment]
Re-opening to consider adding *all* data to AAD. @davidben wrote out the flow if we did this:

- Make your CHInner. This should largely be running through your usual CH assembly logic.
- Encode it with the extensions you expect to compress.
- Make your CHOuter, minus the ECH extension. This should largely run through your existing CH assembly logic.
- Run Deserialize and SetupBaseS.
- Compute CHOuterAAD with half an ECH extension.
- Take EncodedCHInner and CHOuterAAD and run through the context.Seal logic to assemble the final CHOuter.

So, not great, but also not too terrible. I'd prefer we avoid falling into the "gee, I sure wish we bound more to the encryption" state, given the history of ECH, though I agree that this isn't cheap. 

@ekr, what do you think?

**Comment by cjpatton** [comment]
To be clear, the suggestion is to change AEAD encryption so that it authenticates `ClientECH.cipher_suite`, `.config_id`, and `.enc`, correct? This change seems sensible to me. One might argue that this is redundant because these parameters are incorporated into the transcript. On the other hand, ECH usage is resolved before the transcript is known! It seems like a good idea to authenticate these parameters before consuming them.

**Comment by davidben** [comment]
They aren't incorporated on ECH accept, which is mildly interesting. ECH accept also doesn't negotiate with them, so it's probably okay, though there is a "don't stick out" failure (depending on threat model) for the optional config_id flow if we don't authenticate them.
