### ISSUE TITLE
Clarify handling of transcript at client?

### ISSUE THREAD

**Issue by martinduke** [tlswg/draft-ietf-tls-esni#429]
I suspect this is editorial, but it would be helpful to clarify exactly how the client computes its transcript when it generates its keys, based on the permutations of who gets what. IIUC:

* If the server authenticates the inner SNI, the client must construct the client hello as seen by the back-end server, including any OuterExtensions compression, and uses it in the transcript.
* If the server authenticates the public SNI, the client uses the entire client hello in the hash as-is, including the (unreadable) encrypted_client_hello extension.

A server that combines the client-facing and back-end functions also has to duplicate this logic, since it can see everything but maybe shouldn't use it all, and has to go through the motions of formally constructing a proper client hello to a back-end server.

I found this all quite subtle to work out and asked some questions of one of the authors to fully understand. I'll leave it to the editors as to whether the draft needs some text to make this clearer.

[Aside: is it computationally feasible to add some sort of "checksum" that would neutralize the difference in the hashes? That would make this a little less tricky, IMO]

**Comment by sftcd** [comment]
On 06/05/2021 21:27, martinduke wrote:
> I suspect this is editorial, but it would be helpful to clarify
> exactly how the client computes its transcript when it generates its
> keys, based on the permutations of who gets what
+1 and test vectors would be good too

**Comment by sayrer** [comment]
Yes, agree. This is really tricky: "The client presumes acceptance if the last 8 bytes of ServerHello.random are equal to the first 8 bytes of accept_confirmation as defined in Section 7.2. Otherwise, it presumes rejection."

**Comment by sayrer** [comment]
Here's what I ended up writing after I solved this:

"This issue is that the ECH transcript needs to be calculated from an unsent inner ClientHello message, which differs in a few ways from the EncodedClientHelloInner used in HPKE. Upon ECH acceptance, the transcript from the ClientHelloOuter is discarded, then substituted with one calculated from the unsent inner ClientHello message, and the client random is changed to the inner random value. After that, the ServerHello message is added to the transcript as normal. The transcript used for ECH acceptance is separate from the normal transcript."

**Comment by davidben** [comment]
I think the way to think about this is that there are two possible handshakes here, joined at the hip. Either we handshake with ClientHelloOuter, or we handshake with ClientHelloInner. Whichever, we handshake with, we follow the usual RFC8446 rules, including incorporating the chosen ClientHello into the transcript. Indeed on the server, the protocol even supports a client-facing vs. backend server split where the connection is actually rewritten to use ClientHelloInner.

EncodedClientHelloInner, per the name, is just an encoding. We don't want to send two copies of things like key shares. The actual ClientHello being conveyed is still ClientHelloInner. (This is important since the transcript needs to reflect all inputs to TLS parameter negotiation.)

But, yes, on the client this gets a little fun because the client needs to offer these two somewhat related ClientHellos, learn which was to used a message later, and then complete the handshake accordingly.

**Comment by sayrer** [comment]
> But, yes, on the client this gets a little fun because the client needs to offer these two somewhat related ClientHellos, learn which was to used a message later, and then complete the handshake accordingly.

But perhaps there's missing text in "6.1.4.1. Accepted ECH", where client transcript handling could be addressed.

**Comment by martinduke** [comment]
I think we're in agreement here, but is the encoding of ClientHelloInner
deterministic enough that the client-facing server can't possibly express
the expanded ClientHelloInner in a way that breaks the transcript?

**Comment by davidben** [comment]
It's decode, not encode, that needs to be deterministic. And yes, it is deterministic.

**Comment by sayrer** [comment]
Here's what I ended up writing to get this working. I don't have HRR support done yet, so I expect these comments will change a little bit:

```Rust
    pub fn confirm_ech(
        &self,
        ks: &mut KeyScheduleHandshake,
        server_hello: &ServerHelloPayload,
        suite: &SupportedCipherSuite,
    ) -> Result<([u8; 32], HandshakeHash), Error> {
        // The ClientHelloInner prior to encoding.
        let m = self
            .inner_message
            .as_ref()
            .ok_or_else(|| Error::General("No ClientHelloInner".to_string()))?;

        // A confirmation transcript calculated from the ClientHelloInner and the ServerHello,
        // with the last 8 bytes of the server random modified to be zeros.
        let conf = confirmation_transcript(m, server_hello, suite.get_hash());

        // Derive a secret from the current handshake and the confirmation transcript.
        let derived = ks.server_ech_confirmation_secret(&conf.get_current_hash());

        // Check that first 8 digits of the derived secret match the last 8 digits of the original
        // server random. This match signals that the server accepted the ECH offer.
        if &server_hello.random.get_encoding()[24..] != &derived.into_inner()[..8] {
            return Err(Error::General("ECH didn't match".to_string()));
        }

        // Since the ECH offer was accepted, the handshake will move forward with a fresh transcript
        // calculated from the ClientHelloInner, and the handshake should also use the client random
        // from the ClientHelloInner. The ServerHello is added to the transcript next, whether or
        // not the ECH offer was accepted.
        let mut inner_transcript = HandshakeHash::new();
        inner_transcript.start_hash(suite.get_hash());
        inner_transcript.add_message(m);
        Ok((self.inner_random, inner_transcript))
    }
```

**Comment by chris-wood** [comment]
Which transcript is used should be better clarified now that #480 landed. Closing as such. (If we want to track test vectors for ECH, let's open a new issue.)
