### ISSUE TITLE
Reconsider non-HRR ECH acceptance signal

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#441]
Currently, we reuse some bytes of SH.random to signal ECH acceptance when HRR does not occur. Based on [discussion within the context of the HRR design team](https://github.com/tlswg/draft-ietf-tls-esni/wiki/HRR-Design-Team), it may be fruitful to reconsider where this signal goes. Should it in a cleartext extension? Note that this was previously discussed in the context of the original [trial decryption issue](https://github.com/tlswg/draft-ietf-tls-esni/issues/274). It may be worth revisiting this signal's placement as it pertains to the longterm viability of HRR. 

cc @sftcd, @ekr, @martinthomson, @davidben, @cjpatton

**Comment by cbartle891** [comment]
Making ECH acceptance an extension instead of SH.random seems like a good idea if it'll reduce the likelihood of issues with HRR.

> passively inferring whether a server is capable of ECH. (Note that whether or not a server is capable of ECH depends on the attacker’s ability to actively probe, and active attackers are consistent with the ECH threat model.)

I don't think this is a big deal since an attacker can always just try to get the HTTPS RR from DNS to see if the server supports ECH. It's not passive, but it's easy.

**Comment by cjpatton** [comment]
I think this is a question we might try to answer in the initial deployment. Something browsers might consider doing is exercise the ECH codepoint in the server's response by triggering HRR in the inner handshake for some fraction of connection attempts. If these handshake fail at a significantly higher rate then other handshakes, then we know we might have a problem.

**Comment by ekr** [comment]
When I raised this, my reasoning here was about 70% aesthetic and 30% practical. The practical side is that if we always use an extension than it lowers the risk of ossification due to a "Does SH have an ECH extension" filtering. In particular, it seems dangerous to have only SH have the SH.Random hack as we may then discover HRR is broken.

**Comment by davidben** [comment]
I don't think we should make this change. I don't buy it will decrease the likelihood of issues with HRR. Rather, it seems it will increase the likelihood of issues with ECH as a whole.

There are already a lot of TLS 1.3 servers out there, and none of them send ECH extensions in SH. While those servers can and perhaps will eventually be updated, compatibility for _particular_, defined extensions is an early stage risk. Once an extension is wildly deployed, it's already part of selection pressures. Servers may deploy this greasing mechanism faster than ECH itself, but it's an added risk and inefficiency.

For HRR, we're stuck with that risk (and more, because HRR greasing isn't as effective, per https://github.com/tlswg/draft-ietf-tls-esni/issues/450#issuecomment-859667016). For SH, we're not. It doesn't make sense to intentionally take on more risk on SH when it doesn't affect the HRR risk. The incentives are also different here because HRR is so rare.

In particular, if we're worried about the ecosystem allowing ECH + SH, but not ECH + HRR, using the same mechanism won't help. SH and HRR extensions do not use the same syntax, so whether an ecosystem tolerates an extension SH has no relation to whether it tolerates it in HRR. We need to counter the fact that HRR is rare, with strategies like https://crbug.com/677254 (which we have not implemented).

I agree that, aesthetically, the difference is weird. But, I think, practically, the current arrangement is better.

**Comment by martinthomson** [comment]
I'm with @davidben on this.  I can greatly discount the contribution of aesthetics here, leaving very little reason to change and some good reasons not to change forming the bulk of the balance.

**Comment by ekr** [comment]
I can live with this outcome.

**Comment by chris-wood** [comment]
Closing per discussion at IETF 118.
