### ISSUE TITLE
Grease HRR acceptance signal?

### ISSUE THREAD

**Issue by cjpatton** [tlswg/draft-ietf-tls-esni#450]
With #423 we will send an explicit signal of whether ECH was accepted prior to HRR. The mechanism for this is an ECH extension sent by the backend server that contains a pseudorandom string derived from the inner handshake. We need to decide if/how to grease this extension.

**Comment by davidben** [comment]
One way is to say:

* If the ECH client sees an HRR ECH extension whose value is wrong (or, if ECH GREASE, all values are wrong), ignore it. This was an ECH reject. Don't update the ECH extension, and handshake with ClientHelloOuter.
* If a backend server sees a ClientHelloOuter (i.e. has encrypted_client_hello extension pre #422 and has an encrypted_client_hello with type=outer post #422), it sticks a random string into HRR.

**Comment by martinthomson** [comment]
Should the client-facing server grease this as well?

**Comment by chris-wood** [comment]
> Should the client-facing server grease this as well?

If we go with #441, then we probably should for parity.

**Comment by davidben** [comment]
Er, right, I always forget whether our phrasing believes it's the backend or client-facing server responding on ECH reject.

In order for ECH GREASE to work, we need ClientHelloOuter(ech=undecryptable, server_name=A) and ClientHelloOuter(ech=ClientHelloInner(server_name=A)) to result in equivalent handshakes. We could formulate that by saying the client-facing server is purely a ClientHello dispatcher and, reject or accept, it's a backend server you're talking to. Or we could say that, in ECH reject, you're talking to the client-facing server and we assume client-facing server and backend server respond equivalently to server_name=A. If it's the latter then, yeah, this should apply to the client-facing server as well.

**Comment by sftcd** [comment]
Hiya,

On 08/06/2021 22:13, David Benjamin wrote:
> Er, right, I always forget whether our phrasing believes it's the
> backend or client-facing server responding on ECH reject.
> 
> In order for ECH GREASE to work, we need
> ClientHelloOuter(ech=undecryptable, server_name=A) and
> ClientHelloOuter(ech=ClientHelloInner(server_name=A)) to result in
> equivalent handshakes. We could formulate that by saying the
> client-facing server is purely a ClientHello dispatcher and, reject
> or accept, it's a backend server you're talking to. Or we could say
> that, in ECH reject, you're talking to the client-facing server and
> we assume client-facing server and backend server respond
> equivalently to server_name=A. If it's the latter then, yeah, this
> should apply to the client-facing server as well.

I'm not claiming to know the right answer here but I've
started to look at haproxy and split-mode. IIUC (and I
may not) haproxy doesn't want to act as an http server
in any case, so no DocRoot nor any equivalent. (It can
terminate TLS of course but I don't think it ever emits
an HTTP response of it's own creation.)

That may mean, in the event of failed ECH decryption,
(incl. GREASE) or when no ECH key pair is configured
it may make more sense for haproxy to pass on the outer
CH to what it calls a "backend" which is an http server.

Like I say, this is v. preliminary and maybe wrong but
at least for me, I'd not previously considered that the
client-facing server might not be an http server at all.

Put another way - it could be the thing with the ECH
private key is not the thing with the private key that
goes with ECH.public_name.

IOW, I think the kind of description suggested by
David might be a good direction to explore a bit.

Cheers,
S.


>

**Comment by davidben** [comment]
> Don't update the ECH extension

Sorry, this part of my suggestion above doesn't work. I think you need the client to refresh it, otherwise you determine if ECH was accepted just by looking at whether the client changed the extension.

That said, GREASEing this may not be all that useful. It's not too difficult to tell if a server that sent HRR did so with ECH or not, if you're willing to probe the server's behavior on a parallel connection. First, there's this pretty straightforward version:

1. Observe ClientHello and HelloRetryRequest pair from a client and server. Note this only happens if the (client, server) pair would naturally negotiate HRR.
2. Replay ClientHello to that server on a separate connection. You should get HelloRetryRequest with the same parameters because the server's parameter selection is deterministic. (Let's suppose the server did not need to sporadically request a cookie.)
3. See if HelloRetryRequest.ech contained the exact same bytes or not.

HRR contains no server entropy, replaying an ECH ClientHello will give you something consistent, while a naive GREASED implementation will give you different values. We could fix this in one of two ways:

* HRR GREASE should, instead of random bytes, do something deterministic like KDF(server_secret, client_hello), or
* Change ECH confirmation to be a concatenation of some server entropy and the signal computed over the entropy.

But, for that fuss, it doesn't plug the more fundamental distinguisher, which is probably hopeless:

1. Observe ClientHello and HelloRetryRequest pair from a client and server again.
2. Replay ClientHello to that server on a separate connection. You should get HelloRetryRequest with the same parameters again.
3. Second a second ClientHello with a plausible ClientHelloOuter2 and random bytes for the encrypted payload.
4. If the server accepted ECH, it will attempt to decrypt the random bytes, fail, and abort the connection. If the server rejected ECH, it will ignore the payload and handshake with ClientHelloOuter2.

This one seems pretty much fundamental. Deciding ECH at ServerHello sets up handshake secrets at the same time. But deciding ECH at HRR means the server has committed to looking at ClientHelloOuter vs. ClientHelloInner too early. (This is true whether we have an acceptance signal at the client or not. Even in the "apply HRR to both ClientHellos" model, the server has already made a decision, because it needed to in order to decide on HRR at all. That model just had the client learn the decision late.)

**Comment by cbartle891** [comment]
> Er, right, I always forget whether our phrasing believes it's the backend or client-facing server responding on ECH reject.

> In order for ECH GREASE to work, we need ClientHelloOuter(ech=undecryptable, server_name=A) and ClientHelloOuter(ech=ClientHelloInner(server_name=A)) to result in equivalent handshakes. We could formulate that by saying the client-facing server is purely a ClientHello dispatcher and, reject or accept, it's a backend server you're talking to. Or we could say that, in ECH reject, you're talking to the client-facing server and we assume client-facing server and backend server respond equivalently to server_name=A. If it's the latter then, yeah, this should apply to the client-facing server as well.

It only makes sense to me for the client-facing server to be responding on ECH reject. If ECH is rejected, how can it even be expected to know what backend server the client is trying to talk to?

**Comment by cbartle891** [comment]
I think not sticking out is a lost cause, so I don't think it matters whether any GREASE-ing is deterministic or random.

**Comment by davidben** [comment]
> It only makes sense to me for the client-facing server to be responding on ECH reject. If ECH is rejected, how can it even be expected to know what backend server the client is trying to talk to?

The outer ClientHello contains a server name. If you believe the client-facing server is just a dispatcher, then maybe you just dispatch. In particular, if `example.com`'s DNS points to some IP address A and ECH keys, a client that didn't support that ECH cipher, didn't support ECH, or otherwise couldn't get the DNS record would connect to A without offering ECH. But it may still send ECH GREASE, trigger the client-facing server logic, and hit the decryption failure case to handshake ClientHelloOuter.

Although arguably this is already covered by the existing text:

> Otherwise, if all candidate ECHConfig values fail to decrypt the extension, the client-facing server MUST ignore the extension and proceed with the connection using ClientHelloOuter. This connection proceeds as usual, except [...]

https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-7.1-12

Presumably for most deployments, "as usual" would cover whatever name-based dispatch it's happy to do on ClientHelloOuter.

> I think not sticking out is a lost cause (and adds too much complexity), so I don't think it matters whether any GREASE-ing is deterministic or random.

I think I agree that HRR sticking out is hopeless. But then why even bother GREASE-ing here?

**Comment by cbartle891** [comment]
> I think I agree that HRR sticking out is hopeless. But then why even bother GREASE-ing here?

The usual reason: to prevent the ossification of middleboxes.

**Comment by cbartle891** [comment]
> Presumably for most deployments, "as usual" would cover whatever name-based dispatch it's happy to do on ClientHelloOuter.

Ah, right. It's the back-end server then (unless the client-facing server has the name in the CHO, but then you could consider the client-facing server to also be playing the role of a backend server).

**Comment by ekr** [comment]
I thought we had generally agreed that:

(1) We weren't going to worry about parallel connections

```
   achieve stronger security where possible.  Minimally, real ECH is
   designed to be indifferentiable from GREASE ECH for passive
   adversaries with following capabilities: 1.  The attacker does not
   know the ECHConfigList used by the server. 1.  The attacker keeps
   per-connection state only.  In particular, it does not track
   endpoints across connections. 1.  ECH and GREASE ECH are designed so
   that the following features do not vary: the code points of
   extensions negotiated in the clear; the length of messages; and the
   values of plaintext alert messages.
```
(2) We probably couldn't really provide HRR greasing that would work against someone willing to introspect into the connection.

This reasoning is how we got to the extension. I think if we *are* going to do the extension, we probably should have the client-facing server grease to avoid people just filtering connections with ECH in the HRR. But I don't think it has to be very good given the above threat model.

**Comment by chris-wood** [comment]
Closing per discussion at IETF 118.
