### ISSUE TITLE
Proxy Mode

### ISSUE THREAD

**Issue by taoso** [tlswg/draft-ietf-tls-esni#626]
Hi,

I am investigating to detect whether is it possible to implement a SNI proxy using the ECH.

Here is the overview idea.

Instead of using the split mode of ECH, we could implement a specific client-facing server,
which does not require the the original server implement the backend server logic of ECH.

In other word, I suppose to let the client-facing server proxy any TLS traffic according by
the SNI to the normal original server.

However, after some deep digging, I found it is impossible in the current draft. Because
the current draft requires that up on the original backend server accept the ECH handshake,
it will modify the last 8 byte of the random bytes of ServerHello message.

Given we want to implement SNI proxy to original server which will not offer the ECH accept_confirmation,
our client-facing cannot rewrite the server hello random on behalf of backend server since
it will be used to derive the pre-master bytes.

So is it possible to change the mechanism  to transfer the ECH accept_confirmation?

I am wondering if it is appropriate to transfer the ECH accept_confirmation bytes into some
plaintext ServerHello extensions like [Key Share](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.8)
other than the ServerHello random.

If it is possible, we can let the client-facing proxy the ECH TLS traffic to all the current existing
non-ECH-aware TLS server, which will promote the deployment of ECH as much as possible.

**Comment by richsalz** [comment]
Instead of using the split mode of ECH, we could implement a specific client-facing server,
which does not require the the original server implement the backend server logic of ECH.

In other word, I suppose to let the client-facing server proxy any TLS traffic according by
the SNI to the normal original server.

You will probably get more responses if you email the ***@***.******@***.***> mailing list.

Does the client get the certificate from your proxy, and verify it?  If so, why does this need ECH, what benefit does that give?

**Comment by ekr** [comment]
Not seeing any interest in this and we are now in AD review, so closing,
