### ISSUE TITLE
checksum

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-esni#65]
Does the advertisement really need a checksum?  It complicates things for questionable benefit.

Use DNS-over-something-that-isn't-as-lame-as-UDP and this problem goes away.  You probably want DNS to be protected by TLS anyway.

**Comment by kazuho** [comment]
As discussed on https://github.com/ekr/draft-rescorla-tls-esni/pull/23 and https://www.ietf.org/mail-archive/web/tls/current/msg26532.html, I prefer to have the checksum for end-to-end integrity checking and to not have increased risk of service disruption for better adoption of ESNI; otherwise the hosts that using ESNI would stick out.

It's not only when transmitting data over the wire that the ESNIKeys might get corrupt. That could happen before the record gets installed on the authoritative server, or while the data is being cached in a resolver. Or we might have other conveyer in the future.

**Comment by martinthomson** [comment]
Yeah, I don't find those arguments particularly persuasive.  The biggest risk is misconfiguration, which - given the nature of this - won't be persistent.  Sites that do this will test their code and once it is fixed, it should work.

As for network-level corruption, that's rare, and DNS over TLS (or DoH) aren't really vulnerable to that.

**Comment by kazuho** [comment]
I agree that corruption is rare; the question is if it is as rare as TCP transferring corrupt data.

I would like to also point out that corruption cannot be immediately fixed; you need to wait for the cached records to expire. And even if you use DNS over TLS or DOH between the client and the resolver, you could still be using unauthenticated DNS over UDP between the resolver and the authoritative server.

**Comment by chris-wood** [comment]
@kazuho @martinthomson shall we consider this issue resolved?

**Comment by chris-wood** [comment]
Considering resolved.
